Add agent-side functionality for tour scheduling
tiusty/Cocoon pull request #216
Opened 2018-10-31 04:06 UTC by seanrayment

## Changes included in this PR
Allows broker accounts to view unclaimed itineraries at `/scheduler/agentScheduler` and 'claim' itineraries. These itineraries then appear at `/scheduler/myTours`, where brokers can confirm tours by selecting from a list of user provided available start times. 

- [x] URL and view for agents to view pool of unclaimed itineraries 
- [x] AJAX and view functions to support claiming itineraries
- [x] URL and view for agents to view claimed and scheduled itineraries
- [x] AJAX and view functions to support selecting itineraries
- [x] Notifies user by email when a broker has confirmed their itinerary
- [x] AJAX and view functions to support cancelling tour (user side)
- [x] Notifies broker by email when a user has cancelled the tour
- [x] Admin support for itineraries

2018-10-31 15:59 UTC, tiusty commented on cocoon/scheduler/admin.py
> -        ('Tour',
We still want the other fields right? You just want to have the homes show up as raw

2018-10-31 20:30 UTC, tiusty requested changes

2018-10-31 20:30 UTC, tiusty commented on cocoon/scheduler/models.py
> +    def is_claimed(self):
Can you just finish off the function documentation to indicate the return type of the property and what True and False represent

2018-10-31 20:30 UTC, tiusty commented on cocoon/scheduler/models.py
> +    def unschedule_itinerary(self, **kwargs):
Also write what the expected kwargs are in the function doc along with what it does and the return value

2018-10-31 20:30 UTC, tiusty commented on cocoon/scheduler/urls.py
> +    url(r'^myTours/', views.view_tours, name="myTours"),
can you write a comment and then put all the ajax request below saying "these are ajax request". Kinda like what I do for the survey urls

2018-10-31 20:30 UTC, tiusty commented on cocoon/scheduler/views.py
> +def agent_scheduler(request):
I know tests are annoying, but I was thinking that we should start testing the view functions.

More specifically can you test that given a list of itineraries, all the unscheduled itineraries show up? Also test that the itineraries that are scheduled are not in that list. Also test that only broker and admins can see the page

You can either test the view function directly or create a helper module of agent_scheduler functions and just test out that part of the function.

Right now this function is straightforward enough that we may not need tests, but if we have them, then as we add functionality etc, then those tests will become important to verify that we didn't break the page

2018-10-31 20:30 UTC, tiusty commented on cocoon/scheduler/views.py
> +def view_tours(request):
same for above comment.

The tests shouldn't take too long to test but will improve the robustness of the code down the line when we add more funcitonality

2018-10-31 20:30 UTC, tiusty commented on cocoon/scheduler/views.py
> +    """
I think this one is important to test as well.

2018-10-31 20:30 UTC, tiusty commented on cocoon/scheduler/views.py
> +def unschedule_itinerary(request):
ajax functions would be nice to test too if they aren't too difficult

2018-11-06 20:45 UTC, seanrayment commented on cocoon/scheduler/admin.py
> -        ('Tour',
It should still be showing all the fields by default. Let me know if you are seeing something else

2018-11-07 00:35 UTC, seanrayment commented
@tiusty I've added tests if you want to take another look

2018-11-07 00:41 UTC, tiusty commented on cocoon/scheduler/admin.py
> -        ('Tour',
yea they are... my bad

2018-11-07 00:44 UTC, tiusty approved these changes
Just that one minor change and it should be good to go!

2018-11-07 00:44 UTC, tiusty commented on cocoon/scheduler/tests.py
> +def setup_test_itineraries(num_claimed=2, num_unclaimed=2):
minor: can you put these inside the class as member methods? That way there is no chance someone uses them/ they are linked to the Test Class

2018-11-07 01:45 UTC, tiusty approved these changes

2018-11-07 01:45 UTC, tiusty commented on cocoon/userAuth/models.py
> +        print(**extra_fields)
Can you remove this print?

2018-11-07 01:52 UTC, merged

2018-11-07 02:15 UTC, tiusty commented on cocoon/survey/views.py
> +    context = views.get_user_itineraries(request)
@seanrayment This is broken. Could you make a PR hotfix branch to fix this issue on develop?