Client scheduler pr branch
tiusty/Cocoon pull request #218
Opened 2018-10-31 22:40 UTC by akashkumar2296

2018-10-31 22:50 UTC, akashkumar2296 commented
When clicking "Schedule Tours" button, the algorithm is run using user_profile.favorites.all()

This doesn't necessarily hold the scheduler to 1-6 homes but all the favorites of the user. We should change the functionality so that theres a way for the user to only favorite 1-6 before clicking "Schedule tours", or we should run the algorithm separately from the visitList.html page. But as far as I saw, theres no way to change the visit list so the algorithm is being run on all favorites

2018-11-01 00:34 UTC, tiusty requested changes

2018-11-01 00:34 UTC, tiusty commented on cocoon/scheduler/clientScheduler/test_client_scheduler_algorithm.py
> +class TestClientSchedulerAlgorithm(TestCase):
I am not convinced that the alogrithm works at all cases by seeing these tests.
Tests for if the number of nodes is less than 5 would be good, i.e 1, 2 3 etc. Also tests verifying that is working correctly with more configurations. I.e if 2 homes are closer together then 2 homes far away. Then maybe a group of 3 homes close and a group of 2 homes far etc etc.

2018-11-01 00:34 UTC, tiusty commented on cocoon/survey/views.py
> +    for item in interpreted_route:
An imporant part of the route is the time it takes to go between each node. Can you append the edge weight to the itinerary file? Also we need to make sure to add time for each home. So add 20 minutes to ethe estimated to for each home that is stopped at

2018-11-01 00:34 UTC, tiusty commented on cocoon/survey/views.py
> +    itinerary_model = ItineraryModel(client=request.user, selected_start_time=datetime.now())
I would make sure that an itinerary model doesn't already exist before creating one. Otherwise a new itinerary model is created on each page load

2018-11-01 00:34 UTC, tiusty commented on cocoon/scheduler/clientScheduler/client_scheduler.py
> +        self.algorithm = clientSchedulerAlgorithm()
can you have the ClientScheduler inherit the cilentScheduler Algorithm instead of a member data?

2018-11-01 00:34 UTC, tiusty commented on cocoon/scheduler/clientScheduler/base_algorithm.py
> +        :return: starting_point: the Global Minimum. This is the smallest possible distance, so the algorithm will start
can add you add the data type for the arguments and the return type like I did in my function. I.e (int). Do it for the other functions as well

2018-11-06 22:09 UTC, tiusty requested changes

2018-11-06 22:09 UTC, tiusty commented on .gitignore
> +#DS store (mac)
What is this for?

2018-11-06 22:09 UTC, tiusty commented on cocoon/scheduler/clientScheduler/client_scheduler.py
> +        clientSchedulerAlgorithm.__init__(self)
this isn't the correct way to call a parents constructor function,
should be:
`super().__init__()`

2018-11-06 22:09 UTC, tiusty commented on cocoon/scheduler/clientScheduler/client_scheduler.py
> +            result_distance_wrapper = self.wrapper.get_durations_and_distances(origins=[home_one],
you don't want to call the get_durations_and_distances function, use the new retrieve_exact_commutes instead and pass in driving manually to make it clear what it is doing

2018-11-06 22:09 UTC, tiusty commented on cocoon/survey/views.py
> +        itinerary_model = ItineraryModel(client=request.user, selected_start_time=datetime.now())
we do not want the selected_start_time to be set. The selected start time is set when the agent selects a start time based on all the available start times

2018-11-06 22:09 UTC, tiusty commented on cocoon/survey/views.py
> +    itinerary_model.itinerary.save(os.path.basename("itinerary_route_" + str(request.user)) + "_" + str(datetime.now()),
The file path should not be generated here, it should be generated in the model's file like I did for the MLSPIN requester images. I.e create a helper a callable that generates the file path

2018-11-06 22:09 UTC, tiusty commented on cocoon/survey/views.py
> +    itinerary_model.save()
I don't see the homes getting added to the itinerary. The homes that are used to create the route then needs to be saved back into the itinerary so we have a record of what the homes were

2018-11-06 22:09 UTC, tiusty commented on cocoon/scheduler/clientScheduler/base_algorithm.py
> +        min_time = 1000000000
a more robust solution would be to set the min_time to house_matrix[0][1], the first non-zero distance

2018-11-06 22:09 UTC, tiusty commented on cocoon/survey/views.py
> +        AJAX request used to run the client scheduler algorithm and also render the visitList.html page. This is
This comment is not true, this isn't an AJAX request. Anyways when you pull in develop this function will get rewritten anyway.

2018-11-06 22:09 UTC, tiusty commented on cocoon/survey/views.py
> +        :return: HttpResponse if everything goes well. It returns a lot of context variables.
Lol

2018-11-06 22:09 UTC, tiusty commented on cocoon/survey/views.py
> +    homes_list = []
Views are not meant to have a lot of functionality. I updated the renting survey/survey result to reflect that. If you could put this into a def run() function in the client scheduler that would be great. Then you only pass in a few arguments and it does it within the client_scheduler module instead of in the view.

2018-11-07 18:14 UTC, akashkumar2296 commented on .gitignore
> +#DS store (mac)
Its part of the mac OS, .DS_Store should always be gitignored

2018-11-08 16:56 UTC, tiusty commented on cocoon/scheduler/clientScheduler/client_scheduler.py
> +    def __init__(self):
You actually can just delete the __init__() function since it can just inherit it from the base class. It isn't doing anything anymore.

2018-11-08 16:57 UTC, tiusty commented on cocoon/scheduler/models.py
> +def itinerary_directory_path(user):
Actually I meant that it should be a callable for the file_field I can show you at the meeting

2018-11-09 13:45 UTC, tiusty requested changes

2018-11-09 13:45 UTC, tiusty commented on cocoon/scheduler/clientScheduler/tests/test_client_scheduler_wrapper.py
> +        homes_list = ["home1", "home2", "home3"]
Don't you actually want to test with real homes since that is what the function is actually going to be called with? Also add the assertcalledwith functions to assert that the retrieve exact commutes are called properly with the right arguments

2018-11-16 18:53 UTC, tiusty approved these changes

2018-11-16 19:05 UTC, merged