Issue #220 Add React
tiusty/Cocoon pull request #222
Opened 2018-11-05 23:13 UTC by nel-co

1. Adds webpack to bundle React components into `frontend/static/frontend/js/bundle.js`
2. Pass the React component/props through the template `views.py`:
```
context['component'] = 'survey'
context['props'] = 'prop to pass down'
```
3. Inside `templateName.html`, include `react_base` into the `endScripts` block
```
{% block endScripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
    <script src="{% static 'Unicorn/main/navbar.js' %}"></script>
    {% include 'frontend/react_base.html' %} <---- Add this line ----->
{% endblock %}
```
4. After you create a new component, `import` into `frontend/src/index.js` and it to the pages `object`
```
import React from 'react';
import ReactDOM from 'react-dom';

import Survey from './pages/survey/index'; <---- Import Component ---->

const pages = {
    'survey': Survey <---- Add Component Here ---->
};

// This will render the component based on what you pass from `views.py`
ReactDOM.render(
    React.createElement(pages[window.component], window.props),
    window.react_mount
);
```

2018-11-06 01:06 UTC, tiusty requested changes

2018-11-06 01:06 UTC, tiusty commented on .gitignore
> +
Just add a quick note to explain what the git ignore is for

2018-11-06 01:06 UTC, tiusty commented on cocoon/frontend/src/index.js
> +    'survey': Survey
Are we sure we want the index.js to import the survey component? This won't extend to other apps. I feel like we don't want an index.js for all the apps and instead have an index.js for each app kinda like what you did  below. Therefore, should we delete this file?

2018-11-06 01:06 UTC, tiusty commented on cocoon/frontend/src/pages/survey/index.js
> +import React from 'react';
I feel like we shouldn't have the directory structure pages/survey/index.js. I feel like just src/survey/index.js is fine. Each app will have its own directory in src. Let me know if you disagree

2018-11-06 01:06 UTC, tiusty commented on cocoon/static/js/base.js
> +        $(".message_timeout").fadeOut(1500);
wait did you change this? I feel like I added this a while ago

2018-11-06 01:06 UTC, tiusty commented on cocoon/survey/templates/survey/reactRentingSurvey.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
We don't want to duplicate code. You should use the django inheritance (one of the reasons why we are doing a hybrid approach) so you can just inherit the nav bar etc, kinda like what the rentingSurvey.html file does

2018-11-06 01:06 UTC, tiusty commented on cocoon/survey/templates/survey/rentingSurvey.html
> +    <div id="survey"></div>
What does this change do? Is this where the react component going to be loaded?

2018-11-06 01:06 UTC, tiusty commented on cocoon/survey/views.py
> +    context['props'] = 'test'
So I think for now we should leave the old survey page untouched and make a new url for the react survey page. I will make this change tomorrow. Therefore we don't break the old survey page while this page is under development.

2018-11-06 01:06 UTC, tiusty commented on webpack.config.js
> +        exclude: /node_modules/,
Also quick comments describing what each part is doing? I know some of them are trivial but it will make it easier to read especially for someone not as familiar with react

2018-11-06 01:08 UTC, tiusty commented
right now the bundle.js file is included twice (figured one is the old one so you should delete it) but for the other one, I feel like we should not keep it in VC because it will constantly change whenever the react code changes. I know we don't want to download npm and have to compile it on the production machine so we do want to store the production bundle.js but def not the development one. For now can you add the bundle.js to gitingore and then we will try to come up with a good solution for storing the production bundle.js in the VC since it shouldn't change very much

2018-11-06 14:13 UTC, tiusty commented on cocoon/survey/views.py
> +    context['props'] = 'test'
So this is easy once my other PR is merged in, so I will merged that in later today and then I will make that change. In the mean time you can work on the other changes!

2018-11-06 22:16 UTC, nel-co commented on cocoon/static/js/base.js
> +        $(".message_timeout").fadeOut(1500);
I had to add it back in since it was missing for some reason. Didn't change anything though.

2018-11-07 22:38 UTC, nel-co commented
Just tested, everything's still working. 👍

2018-11-07 22:44 UTC, tiusty commented on cocoon/static/js/base.js
> +        $(".message_timeout").fadeOut(1500);
This file is still in develop, it is in cocoon/static/cocoon/js/base.js so could you remove this one? If there is an issue with importing it then we should figure out why

2018-11-07 22:46 UTC, tiusty approved these changes
Once the base.js file is removed, and tested that it still works. It should be good to merge!

2018-11-07 22:55 UTC, nel-co commented on cocoon/static/js/base.js
> +        $(".message_timeout").fadeOut(1500);
No issues with importing. When I first ran webpack while setting it up, it replaced this file in static/js with the bundle so I had to recreate it. All fixed now though.

2018-11-08 00:13 UTC, merged