Issue 244 currently available fix
tiusty/Cocoon pull request #254
Opened 2019-01-04 19:36 UTC by seanrayment

#### Note:
This PR must be merged after #253 as it has been re-based to include the model changes incorporated in that PR.

### Description

This PR adds another static filter to fix the bug described in #244

2019-01-04 19:38 UTC, seanrayment commented on cocoon/survey/cocoon_algorithm/base_algorithm.py
> +            .filter(last_updated=F('listing_provider__last_updated_feed')) \
This is the relevant line to be reviewed (the rest of the diff is only relevant to #253 )

2019-01-07 04:39 UTC, tiusty commented on cocoon/survey/cocoon_algorithm/base_algorithm.py
> +            .filter(last_updated=F('listing_provider__last_updated_feed')) \
cool, once the other PR is in I will do a last review of this one

2019-01-08 21:17 UTC, seanrayment commented on cocoon/survey/cocoon_algorithm/base_algorithm.py
> +            .filter(last_updated=F('listing_provider__last_updated_feed')) \
Other PR and unittests are in!

2019-01-09 01:04 UTC, tiusty requested changes

2019-01-09 01:04 UTC, tiusty commented on cocoon/survey/cocoon_algorithm/cocoon_algorithm_tests/tests_base_algorithm.py
> +        ygl_provider.last_updated_feed = timezone.now()
calling timezone.now() independently makes this unittest somewhat undeterministic because there is a slight timedelta which probably will never cause an issue but could so lets avoid it.

maybe do something like:
time_updated =timezone.now()

then pass in time_updated to all the functions and do the time delta on the time_updated function. 

This will make it more deterministic (granted the timezone.now() is in itself undeterministic....) because then we are using the same exact time value instead of slightly off. I know this is even more mitigated by the fact that the home provider only stores the date which truncates off the time anyways but I think it should be easy and worth while to fix.

2019-01-09 04:06 UTC, tiusty commented on cocoon/survey/cocoon_algorithm/cocoon_algorithm_tests/tests_base_algorithm.py
> +        ygl_provider.last_updated_feed = timezone.now()
Also I was reading that the setup method should be avoided... could you create a new test class and then you can create the provider model in that function with the time_updated variable as per above. Therefore we know the homes and the home provider model will have the exact same time.

2019-01-09 19:47 UTC, seanrayment commented on cocoon/survey/cocoon_algorithm/cocoon_algorithm_tests/tests_base_algorithm.py
> +        ygl_provider.last_updated_feed = timezone.now()
By the setup method do you mean calling `create_home`?

2019-01-10 01:06 UTC, tiusty approved these changes
Looks good!

2019-01-10 23:07 UTC, merged