Issue 184 home data ml
tiusty/Cocoon pull request #266
Opened 2019-01-10 04:31 UTC by akashkumar2296

- Finished word scraper for mls
- Updated form to look for all amenities
- Added filtering in cocoon algorithm to find relevant homes

2019-01-10 04:47 UTC, tiusty requested changes
The biggest thing is the orgainzation of which fields go with which class. We should try to keep it constant with the survey model and house data model. They won't all be identical but we should try to keep it similar

2019-01-10 04:47 UTC, tiusty commented on cocoon/houseDatabase/management/commands/tests/tests_word_scraper.py
> +
Since we have the file in the helpers directory, could you actually make the tests directory in the helper directory and then put the tests there?

2019-01-10 04:47 UTC, tiusty commented on cocoon/houseDatabase/management/commands/helpers/word_scraper.py
> +    def __init__(self):
can you add the adding the input description to the constructor?

2019-01-10 04:47 UTC, tiusty commented on cocoon/houseDatabase/models.py
> +    laundromat_nearby = models.BooleanField(default=False)
Not sure if I like this here because it is kinda different then what I was going for that class.

Can you make a new class called HouseNearbyAmenitiesModel or something? We are gonna add stuff for nearby things at some point anyways

2019-01-10 04:47 UTC, tiusty commented on cocoon/survey/forms.py
> +class AmenitiesForm(ModelForm):
I would try to separate out of the Amenities like the survey model. 

I ideal the form classes would match to the survey so we want an ExteriorAmenitiesForm, InteriorAmentiesForm etc.

2019-01-10 04:47 UTC, tiusty commented on cocoon/survey/forms.py
> +class AmenitiesForm(ModelForm):
You also seem to be missing the laundry_nearby survey form field

2019-01-10 04:47 UTC, tiusty commented on cocoon/survey/models.py
> +    number_of_dogs = models.IntegerField(default=0)
these form fields are duplicated from the Interior Amenities. We want the amenities seperated by type so it doesn't become a huge list for one class. Try to follow what we categorized them in the house database model.

2019-01-10 04:52 UTC, akashkumar2296 commented on cocoon/survey/forms.py
> +class AmenitiesForm(ModelForm):
Thats how I had it at first, but I was running into a meta class error when I tried importing both of them to RentSurveyModel

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

I struggled with this pretty hard so I just put them all together to make it work. If you can find a solution to this, let me know, because I looked pretty hard and the only solutions I found we're really hacky.

2019-01-10 04:54 UTC, tiusty commented on cocoon/survey/forms.py
> +class AmenitiesForm(ModelForm):
not sure why you would have that error cus I am inheriting other form classes into the SurveyForm already so it should just be identical to what I have. Try again and if you get the same issue show me and I will resolve it

2019-01-10 04:54 UTC, tiusty commented on cocoon/survey/forms.py
> +class AmenitiesForm(ModelForm):
was there something different about the class you were doing?

2019-01-11 19:34 UTC, akashkumar2296 commented on cocoon/survey/forms.py
> +class AmenitiesForm(ModelForm):
Nope, nothing at all. It was identical to the exterior amenities class. For some reason it just would not work

2019-01-11 19:34 UTC, akashkumar2296 commented on cocoon/survey/models.py
> +    number_of_dogs = models.IntegerField(default=0)
^ Same issue as above. They were originally separated but I had to combine them

2019-01-19 00:50 UTC, tiusty requested changes
Also can you remove those other idx feed files which are not necessary

2019-01-19 00:50 UTC, tiusty commented on cocoon/houseDatabase/management/commands/mlspin/MlspinRequester.py
> +                if word_scraper.word_finder(["laundromat","nearby"]):
now the proximity of words we shouldn't set the other ones to false. A home can have multiple of the laundry features at once... i.e it can have in building and nearby

2019-01-20 22:02 UTC, tiusty approved these changes

2019-01-22 20:06 UTC, merged