Issue 256 add map for drawing
tiusty/Cocoon pull request #269
Opened 2019-01-11 18:13 UTC by tiusty

Now the user can draw an area if they so desire to filter homes outside of that area

2019-01-15 03:18 UTC, seanrayment requested changes
Looks great on the frontend and storing polygons in the db is awesome. Just found one bug regarding invalid polygons that are allowed on the frontend but break shapely's `Polygon` constructor. After that and maybe a unit test for `save_polygons` should be good to go!

2019-01-15 03:18 UTC, seanrayment commented on cocoon/survey/cocoon_algorithm/base_algorithm.py
> +            polygon = Polygon(vertices)
I think there is one more layer of error-checking that needs to be done between translating the frontend polygon representation into the shapely one. I was able to draw both 1-vertex and 2-vertex polygons in google maps that caused a `ValueError: A LinearRing must have at least 3 coordinate tuples` on this line. 

Actually, on second thought, it would make sense to check that the polygon will by a valid shapely polygon in the `save_polygons` function so that a user cannot submit a broken survey form.

2019-01-15 03:18 UTC, seanrayment commented on cocoon/frontend/src/survey/rentForm/general/generalForm.js
> +        /* Draws all the polygons stored in the state */
Funny enough, since this comment is nested in the JSX, it actually gets rendered in the HTML as text. It's mostly covered by the "Delete All Areas" button, but still visible.

![draw_on_map_comment](https://user-images.githubusercontent.com/10607620/51155414-6b172600-1845-11e9-9948-6bf590012a5e.png)

2019-01-15 03:18 UTC, seanrayment commented on cocoon/frontend/src/survey/rentForm/main/index.js
> +    handleCompletePolygon = (p) => {
It might be nice to also have frontend validation that the polygon is valid in here. i.e.
```
if vertices.length < 3 {
    alert("Selected area must have at least 3 points") // ideally a less intrusive error message xD
    this.deletePolygon()
}
```

2019-01-15 03:18 UTC, seanrayment commented on cocoon/frontend/src/survey/rentForm/main/index.js
> +        let verticies = [];
totally nitpicking but I think the spelling is "vertices"

2019-01-15 20:19 UTC, tiusty commented on cocoon/survey/cocoon_algorithm/base_algorithm.py
> +            polygon = Polygon(vertices)
Yea good catch!

2019-01-15 20:20 UTC, tiusty commented on cocoon/survey/cocoon_algorithm/base_algorithm.py
> +            polygon = Polygon(vertices)
yes I was being lazy... so thanks for calling me out on not unit testing lol

2019-01-16 00:39 UTC, tiusty commented
@seanrayment Should be all set!

My only unsure thing was when we do the edit survey... we need to check if the polygons exist already before adding them... since this is not trivial right now I am going to push it off to the new survey results page. My plan is that when the polygon is pulled from the server it has the id stored in the dictionary (and ones created by the page won't) so then I can just match by id of the polygon. I tried to implement a polygon vertices matching thing but it is messy and think it will be better by id. That is unless you can think of a better way

2019-01-16 18:17 UTC, seanrayment approved these changes
LGTM!

2019-01-16 19:14 UTC, merged