Updates home tile styling and adds additional props
tiusty/Cocoon pull request #274
Opened 2019-01-17 21:03 UTC by nel-co

This PR updates the home tile style to match figma mockups. Adds props `canFavorite` and `canVisit` to determine which buttons to render on the tile. Adds `isLarge` prop to determine how to render the tile. i.e. horizontal or square.

2019-01-17 21:32 UTC, nel-co commented
Just realized I need to fix the border-radius on the images when the tile is the larger one.

2019-01-17 21:44 UTC, tiusty requested changes
Couple minor comments.

The other thing that needs to get changed is that bug via removing home from visit list as we discussed on slack

2019-01-17 21:44 UTC, tiusty commented on cocoon/frontend/src/common/homeTile/homeTile.js
> +        // Toggles whether the home text depending on favorite status
This comment is wordly weirdly.

2019-01-17 21:44 UTC, tiusty commented on cocoon/frontend/src/common/homeTile/homeTiles.js
>                      home={this.props.homes.find(home => home.id === this.state.home_click_id)}
can we replace the home={filter()} with the home you used so it is consistent. This prevents doing the filter twice.

2019-01-20 20:07 UTC, tiusty approved these changes

2019-01-20 21:39 UTC, merged