#133 Restyles the homepage to match figma design
tiusty/Cocoon pull request #308
Opened 2019-02-01 20:20 UTC by nel-co

2019-02-01 22:15 UTC, tiusty requested changes
Overall looks good, some changes that I think are worth while

2019-02-01 22:15 UTC, tiusty commented on cocoon/homePage/templates/homePage/landingPage.html
> +          <button>nelsonc19@gmail.com <i class="material-icons">arrow_drop_down</i></button>
this is hardcoded, this should be dynamically renderd
i.e {{ user.email }} I am pretty sure

2019-02-01 22:15 UTC, tiusty commented on cocoon/homePage/templates/homePage/landingPage.html
> +        <a href="{% url 'userAuth:surveys' %}">My Surveys</a>
we actually only want to render the surveys and itineraries if the user is a hunter
so 
{% if user.is_hunter %}

2019-02-01 22:15 UTC, tiusty commented on cocoon/homePage/templates/homePage/landingPage.html
> +    <div class="nav-links_mobile">
I like the mobile drop down, but at least on the home page, if you go to the mobile view, the nav bar and the area on the top of the page are the same color, so we should try to fix that... maybe with an outline or something. It looks weird with the brick on brick

2019-02-01 22:15 UTC, tiusty commented on cocoon/homePage/templates/homePage/landingPage.html
> +    <div class="nav-links_mobile">
Maybe we should make that button line more defined so it looks like a different section

2019-02-01 22:15 UTC, tiusty commented on cocoon/homePage/templates/homePage/landingPage.html
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.1/min/tiny-slider.js"></script>
is there anyway to download this and then store them in with our static files?

2019-02-01 23:27 UTC, tiusty commented on cocoon/homePage/templates/homePage/landingPage.html
> +          <a href="#">Agent Portal</a>
I realized that these url links are not set up either

2019-02-01 23:28 UTC, nel-co commented on cocoon/homePage/templates/homePage/landingPage.html
> +          <a href="#">Agent Portal</a>
oh good catch!

2019-02-02 16:47 UTC, tiusty approved these changes

2019-02-02 16:48 UTC, tiusty commented
Looks good to me!

2019-02-02 17:38 UTC, merged