Feature/modularize algorithm retrieving data
tiusty/Cocoon pull request #36
Opened 2018-01-09 16:16 UTC by seanrayment

2018-01-10 01:00 UTC, tdefroscia commented
All tests are passing, so probably safe to merge, but Alex definitely should OK everything first.

2018-01-10 01:27 UTC, tiusty commented on houseDatabase/management/commands/pull_mlspin.py
> +class MlspinRequester:
Could we write the class comments for this class. Aka to know what it does and the data types for each member variable

2018-01-10 01:27 UTC, tiusty commented on houseDatabase/management/commands/pull_mlspin.py
> +        print(len(lines))
we should remove debugging lines from the PR?

2018-01-10 01:27 UTC, tiusty commented on houseDatabase/management/commands/pull_mlspin.py
>  class Command(BaseCommand):
Could we also comment this class

2018-01-10 01:27 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                        new_in_database = home.calculate_approx_commute(home.home.zip_code, destination, "driving")
This should not be hardcoded since we want to support multiple commute types. Since rent algorithm inherits CommuteAlgorithm it should support the self.commute_type from that class

2018-01-10 01:27 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                in_database = home.calculate_approx_commute(home.home.zip_code, destination, "driving")
This should also not be hardcoded per other comment

2018-01-10 01:27 UTC, tiusty commented on survey/cocoon_algorithm/base_algorithm.py
>  class CocoonAlgorithm(object):
The class comments should be updated (I can do this one)

2018-01-10 01:27 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                compute_approximates.approximate_compute_handler(origin_list, destination, "driving")
Should also not be just driving

2018-01-10 01:27 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                results = distance_matrix_requester.calculate_distances(origin_addresses, [destination_address])
Shouldn't this take in a commute type?

2018-01-10 01:27 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +        for home in self.homes:
I would prefer not to call the variable home since it isn't a home.
Before I did:
for home_data in self.homes to differentiate from the home stored in the homeScore
but maybe this would be better:
for home_score in self.homes:

2018-01-10 01:27 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +        for home in self.homes:
I have done this too and I should probably fix mine as well

2018-01-10 01:27 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                for i in range(min(len(self.homes[:number_of_exact_commutes_computed]), len(results))):
Can you comment on what this is doing? I think I know but a lot of things are happening

2018-01-10 01:27 UTC, tiusty commented on survey/distance_matrix/compute_approximates.py
> +def approximate_compute_handler(origins_zips_states, destination_zip_state, commute_type):
Is it supposed to be, compute or commute? Maybe a better name would be calculate_approximate_commute

2018-01-10 01:27 UTC, tiusty commented on survey/distance_matrix/compute_approximates.py
> +    return results
why do we need a return value? I feel like a boolean saying if it succeeded for failed is fine.

2018-01-10 01:27 UTC, tiusty commented on survey/distance_matrix/compute_approximates.py
> +    return results
It looked like the return isn't even being used in the code

2018-01-10 01:27 UTC, tiusty commented on survey/distance_matrix/distance_wrapper.py
> +
Class comments would be good

2018-01-10 01:27 UTC, tiusty commented on survey/distance_matrix/distance_wrapper.py
> +
i.e 
    """
    Class included the base values for any algorithm.

      Attributes:
        self._homes (List[HomeScore]): Stores a list of homes as a HomeScore
        self._destinations (List[anything that inherits survey.models.DestinationsModel]): The desired destinations
            specified by the user. These locations are the work, schools that the user needs to go to.

    """

2018-01-10 01:28 UTC, tdefroscia commented on houseDatabase/management/commands/pull_mlspin.py
> +        print(len(lines))
Yes

2018-01-10 01:29 UTC, tdefroscia commented on survey/cocoon_algorithm/rent_algorithm.py
> +                        new_in_database = home.calculate_approx_commute(home.home.zip_code, destination, "driving")
This is definitely the correct approach, will change.

2018-01-10 01:32 UTC, tdefroscia commented on survey/cocoon_algorithm/rent_algorithm.py
> +                results = distance_matrix_requester.calculate_distances(origin_addresses, [destination_address])
Sean will have to take a look at this

2018-01-10 01:32 UTC, tdefroscia commented on survey/cocoon_algorithm/rent_algorithm.py
> +                for i in range(min(len(self.homes[:number_of_exact_commutes_computed]), len(results))):
Also for Sean to look at

2018-01-10 06:09 UTC, tiusty requested changes
Distance matrix comments

2018-01-10 06:09 UTC, tiusty commented on survey/distance_matrix/distance_wrapper.py
> +            if (len(origin_list) > 25):
This will fail if there is more than one destination. The distance matrix api can only take 25 elements. An element is defined by (origins * destinations) = element. So the amount the list should be spliced by should be variable depending on the number of destinations. So if there are 2 destinations than 25/2 origins should also be included
@seanrayment

2018-01-10 06:09 UTC, tiusty commented on survey/distance_matrix/distance_wrapper.py
> +                response_json = distance_matrix.distance_matrix(self.client,
This should also take in commute type
@seanrayment

2018-01-10 06:09 UTC, tiusty commented on survey/distance_matrix/distance_wrapper.py
> +            if (len(origin_list) > 25):
I also feel like having the two cases is redundant. Can't you just use the first case for all of it? because origin_list = origin_list[25:] will go to empty if there is less than 25 elements. Also for the origin size you could do something list origing_list[:25//len(destinations)] and for destinations just destinations[:25]. We should think of the best solution but it might be best to make that one case
@seanrayment

2018-01-10 06:14 UTC, tiusty requested changes
More minor things

2018-01-10 06:14 UTC, tiusty commented on survey/home_data/home_score.py
> +    def calculate_approx_commute(self, origin_zip, destination, commute_type):
I kind of don't like the name of this function anymore. It doesn't really calculate the approx commute, it more checks to see if the zip code is cached. Maybe change the name to like, populate_approx_commutes or something like that.
  @tdefroscia

2018-01-10 06:14 UTC, tiusty commented on survey/home_data/home_score.py
> +        or if the pair wasn't valid. The last 2 entries are the origin and destination zip respectively.
Also update this documentation since you got rid of the return values
  @tdefroscia

2018-01-10 06:25 UTC, tiusty commented
The PR looks good! I just commented what I think should be changed but let me know if you think otherwise! Once we talk/resolve those issues we should be good to go!

2018-01-10 06:26 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                results = distance_matrix_requester.calculate_distances(origin_addresses, [destination_address])
@seanrayment

2018-01-10 06:26 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                for i in range(min(len(self.homes[:number_of_exact_commutes_computed]), len(results))):
@seanrayment

2018-01-10 06:39 UTC, tiusty commented on survey/home_data/home_score.py
> +    def calculate_approx_commute(self, origin_zip, destination, commute_type):
also I think it can stay in HomeScore because it populates the variable in HomeScore but let me know if you think otherwise

2018-01-10 16:46 UTC, tiusty requested changes
Minor change requested

2018-01-10 16:46 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
>                          if new_in_database != True:
I would change this to not in_database like you did earlier
@tdefroscia

2018-01-10 18:03 UTC, seanrayment commented on survey/cocoon_algorithm/rent_algorithm.py
> +                results = distance_matrix_requester.calculate_distances(origin_addresses, [destination_address])
The DistanceWrapper obj defaults to "driving" but I will update this to make it clearer

2018-01-10 18:09 UTC, seanrayment commented on survey/cocoon_algorithm/rent_algorithm.py
> +                for i in range(min(len(self.homes[:number_of_exact_commutes_computed]), len(results))):
Thanks for taking note of this one, it was unnecessarily complex. Fixed!

2018-01-10 18:11 UTC, seanrayment commented on survey/distance_matrix/compute_approximates.py
> +def approximate_compute_handler(origins_zips_states, destination_zip_state, commute_type):
commute! thank you

2018-01-10 18:14 UTC, seanrayment commented on survey/distance_matrix/compute_approximates.py
> +    return results
I guess the return type isn't necessary because it catches an exception on failure.

2018-01-10 18:19 UTC, seanrayment commented on survey/distance_matrix/distance_wrapper.py
> +
Added

2018-01-10 19:32 UTC, tiusty requested changes

2018-01-10 19:32 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                results = distance_matrix_requester.calculate_distances(origin_addresses, [destination_address])
ah I see, in the constructor of DistanceWrapper it sets it to driving.Then the constructor should take in mode-self.commute_type so it can support another commute type. I am not a big fan of that because it is confusing, Since calculate_distance (which should be renamed because it also gets time), is the only function that uses commute type, maybe it should be passed in instead and removed as a member variable?
@seanrayment

2018-01-11 17:11 UTC, tiusty requested changes

2018-01-11 17:11 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                                                                                mode="driving")
is there any reason why we can't do mode=self.commute_type? Right now the rent_algorithm itself defaults to driving. That we the rent algorithm can work with other commute types

2018-01-11 17:11 UTC, tiusty commented on survey/distance_matrix/compute_approximates.py
> +                                                  mode="driving")
same with here, since the commute_type is passed in could mode=commute_type? and then the mode can be removed from the constructor. Sorry if you are gonna do that anyways.

2018-01-11 17:16 UTC, seanrayment commented on survey/cocoon_algorithm/rent_algorithm.py
> +                                                                                mode="driving")
The reason I didn't do that is because I thought our commute_type was "Driving" and the googlemaps package uses "driving." Although I suppose it would be simple enough to change our model

2018-01-11 17:17 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                                                                                mode="driving")
it actually supports driving, walking, biking and transit. Right now driving is the only tested one. I would like to get the other ones tested and reliable soon enough. The model field itself is a choice field with all 4 options

2018-01-11 17:23 UTC, seanrayment commented on survey/cocoon_algorithm/rent_algorithm.py
> +                                                                                mode="driving")
I'm referring to the "D" vs. "d". googlemaps expects lower case strings, but looking again I think our models are lowercase as well, so I can change that

2018-01-11 17:25 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                                                                                mode="driving")
yea the model is receiving from global config: 

COMMUTE_TYPES = (
    ('driving', 'Driving'),
    ('transit', 'Transit'),
    ('walking', 'Walking'),
    ('biking', 'Biking'),
)

So i think it will display it with D, but then actually save it with d. Let me know if that is wrong.

2018-01-11 17:49 UTC, seanrayment commented on survey/distance_matrix/distance_wrapper.py
> +            if (len(origin_list) > 25):
Looking back over the distance matrix documentation. A request can have 100 elements and a maximum of 25 destinations or origins. This would support up to 4 destinations. Shouldn't that be enough?

2018-01-11 18:01 UTC, tiusty commented on survey/distance_matrix/distance_wrapper.py
> +            if (len(origin_list) > 25):
yea... you are right it is 100 elements, then what I was saying later is wrong.

2018-01-11 18:29 UTC, tiusty requested changes

2018-01-11 18:29 UTC, tiusty commented on survey/cocoon_algorithm/rent_algorithm.py
> +                for i in range(min(number_of_exact_commutes_computed), len(results)):
Unit tests were failing due to a bug on this line. The parentheses are messed up. The min should encompass both of the elements. Good thing for unit tests! I could change it but since it your code I will let you do it to prevent confusion.
@seanrayment

2018-01-11 18:32 UTC, tiusty approved these changes

2018-01-11 18:35 UTC, merged