Results page and Map Marker updates
tiusty/Cocoon pull request #426
Opened 2019-03-21 19:32 UTC by nel-co

This closes #400, #403, and #407 
- Shows more info on the results page map when hovering over home tile/map marker or the home tile is open
- On the results page, when a user clicks the home tile the map marker is centered on the map
- Adds ability to toggle between map/results view on mobile

2019-03-26 15:20 UTC, tiusty requested changes
Added some requests in slack

2019-03-27 08:42 UTC, tiusty commented on cocoon/frontend/src/survey/resultsPage/map/map.js
> +    createBounds = () => {
I am kinda confused what is happening here. Do you mind commenting the code more so it is more clear?

2019-03-27 08:43 UTC, tiusty commented on cocoon/frontend/src/survey/resultsPage/map/map.js
> +    createBounds = () => {
Also this seems to just adjust the center lat/lng so how does it set the zoom size?

2019-03-28 13:33 UTC, nel-co commented on cocoon/frontend/src/survey/resultsPage/map/map.js
> +    createBounds = () => {
the `createBounds()` was initially going to use the `fitbounds()` method from google maps, but I couldn't get it to work. `fitbounds()` would take the coordinates and center the map around them and set the zoom to a level where they're near the edge.  Since that couldn't happen, `createBounds()` now just sets the center of our map based on the homeTile cooridinates and the zoom level is fixed.

2019-03-28 13:50 UTC, tiusty commented on cocoon/frontend/src/survey/resultsPage/map/map.js
> +    createBounds = () => {
ah, I will look into fitbounds now

2019-03-30 01:34 UTC, merged