Issue 417 fix word scraper
tiusty/Cocoon pull request #467
Opened 2019-04-17 18:59 UTC by akashkumar2296

- fixed function calls
- fixed repretitve words issue

2019-04-18 14:41 UTC, tiusty requested changes
Few changes

2019-04-18 14:41 UTC, tiusty commented on cocoon/houseDatabase/management/commands/helpers/word_scraper.py
> +        return self.word_finder([pet, "allowed"]) and not self.word_finder(["no",pet, "allowed"])
Pretty sure the pet here shouldn't be a variable and should be surrounded by quotation? did that compile??

2019-04-18 14:41 UTC, tiusty commented on cocoon/houseDatabase/management/commands/mlspin/MlspinRequester.py
> +                new_listing.laundromat_nearby = word_scraper.look_for_laundromat()
So side note, this script is deprecated and not used anymore.

Now we are using the RETSRequester script instead of the MLS. Could you add the word scrapping there? It is good that we updated this script too in case we ever have to revert to using this. Sorry should have mentioned that

2019-04-18 14:41 UTC, tiusty commented on config/keys/keys_filepaths.py
> +    'DOCUSIGN_PRIVATE_KEY_DEV': os.path.join(BASE_DIR, 'keys', "docusign_private_key_prod.txt"),
you shouldn't have to and also shouldn't use the production keys, cus this will affect our production environment. Make sure to use the private keys and download the correct file if needed

2019-04-18 14:42 UTC, tiusty commented on .gitignore
> +cocoon_updated/
Also this shouldn't be necessarily so can we remove this?

2019-04-18 17:53 UTC, akashkumar2296 commented on cocoon/houseDatabase/management/commands/helpers/word_scraper.py
> +        return self.word_finder([pet, "allowed"]) and not self.word_finder(["no",pet, "allowed"])
I realized that we were doing "cats" and "dogs" the same exact way so I made pet a variable in the function signature so that its not repetitive code.

2019-04-18 19:20 UTC, tiusty requested changes
Last things

2019-04-18 19:20 UTC, tiusty commented on config/keys/keys_filepaths.py
> +    'DOCUSIGN_PRIVATE_KEY_DEV': os.path.join(BASE_DIR, 'keys', "docusign_private_key_dev.txt"),
We should just leave these to what they were beforehand. So just revert this change

2019-04-18 19:20 UTC, tiusty commented on cocoon/houseDatabase/management/commands/mls_rets/MLSRetsRequester.py
> +            new_listing.air_conditioning = word_scraper_remarks.look_for_ac()
well so this actually isn't good because we only want to set the response if it is true. That is because usually the value will set if it in the above line. So this is a second check to set it true if it exists in the word scrapper. This will set it to false if it can't find it in the word scrapper

2019-04-18 19:20 UTC, tiusty commented on cocoon/houseDatabase/management/commands/helpers/word_scraper.py
> +        return self.word_finder([pet, "allowed"]) and not self.word_finder(["no",pet, "allowed"])
oh I missed that

2019-04-18 19:21 UTC, tiusty commented on cocoon/houseDatabase/management/commands/mls_rets/MLSRetsRequester.py
> +            new_listing.air_conditioning = word_scraper_remarks.look_for_ac()
we actually just want to do what it was doing before, so I would just revert this change as well

2019-04-19 01:31 UTC, tiusty approved these changes
Looks good to me!

2019-04-19 04:52 UTC, merged