Mls fix
tiusty/Cocoon pull request #81
Opened 2018-02-08 16:23 UTC by seanrayment

I think the best way to go about it would be to leave move_in_day in the model for use later on. Then last_updated and is_available work together. 

Maybe in the pre-survey static filtering we designate all apartments where the last_updated does not match the last_updated_database to is_available=false. Then we exclude all homes that are not available.

2018-02-09 04:31 UTC, tiusty requested changes
Overall looks good but think a few changes would be benificial

2018-02-09 04:31 UTC, tiusty commented on houseDatabase/models.py
> +class DatabaseManagementModel(models.Model):
I think we should start creating database managers per apartment feed. So instead of being a generic database manager, it can be just for the MLS feed. So I would call this MLSManagementModel or something like that. Then if we get other feeds then they can have separate managers depending on how the data is fed etc

2018-02-09 04:31 UTC, tiusty commented on houseDatabase/management/commands/pull_mlspin.py
> +        manager.last_updated_database = timezone.now()
to be consistent so there isn't weird issues if the script is called before midnight and then finishes after midnight. I think you should get the time when the script is called and then use that time for when all the homes are updated and when the homes are last updated (aka the databaseManagementModel thing)

2018-02-09 04:31 UTC, tiusty commented on houseDatabase/management/commands/pull_mlspin.py
> +                if (list_type == "RN"):
what does RN mean? Could you comment what is happening a little more? That would be super helpfull so I don't have to figure it out! :)

2018-02-09 04:33 UTC, tiusty commented
Also commenting on your previous comment. I would prefer if the move_in_day stuff is removed since it is kinda dead code right now. It is easy enough to implement so if later we need it, we can easily add it and reimplement it the correct way based on the data feed. You could also make the argument that is_available is useless right now too.... so I could remove that if you think it has no point.

2018-02-09 04:42 UTC, tiusty commented on houseDatabase/management/commands/pull_mlspin.py
> +                except ValueError:
If the fields aren't ints should the home be immediately disqualified? What is the downside of doing nothing?

2018-02-09 04:42 UTC, tiusty commented on houseDatabase/management/commands/pull_mlspin.py
> +        manager = DatabaseManagementModel.objects.get(pk=1)
I don't like this method of retrieving the object cus for some reason, if it gets deleted and then gets recreated, then it won't be pk=1, it would be pk=2. Maybe we can think of a better way of retrieving the object? Maybe just DatabaseManagementMode.objects.all().first() or something. Up to you. Hopefully, we can assume that there would only be one object. You can look at this post to see how to override the save() method so only one object of the model can ever exist (in essence making it a singleton) https://stackoverflow.com/questions/39412968/allow-only-one-instance-of-a-model-in-django

2018-02-09 04:42 UTC, tiusty commented on houseDatabase/management/commands/pull_mlspin.py
> +        manager = DatabaseManagementModel.objects.get(pk=1)
I can also work on it if you don't want to do it

2018-02-09 04:43 UTC, tiusty commented
side note.... so nice not to have  PR with 30k lines changes haha

2018-02-09 16:16 UTC, seanrayment commented on houseDatabase/models.py
> +class DatabaseManagementModel(models.Model):
Agreed

2018-02-09 16:16 UTC, seanrayment commented on houseDatabase/management/commands/pull_mlspin.py
> +        manager.last_updated_database = timezone.now()
Yup, good call

2018-02-09 16:17 UTC, seanrayment commented on houseDatabase/management/commands/pull_mlspin.py
> +                if (list_type == "RN"):
I'll clarify in a comment, but "RN" is the plaintext in the MLS feed that denotes the listing is a rental.

2018-02-09 16:23 UTC, seanrayment commented on houseDatabase/management/commands/pull_mlspin.py
> +                except ValueError:
This is to protect against typos in the MLS feed, which is currently giving us a ValueError in the live version. So if the number_bathrooms field contains "c" in plaintext it triggers the ValueError and we skip the home. 

Let me know if that's not what you were asking about.

2018-02-10 19:49 UTC, tiusty approved these changes
Looks good! Quick questions. Was this working for you on your local machine? When I took your branch it wasn't running because of some missing imports etc. I ended up committing them.

2018-02-10 19:49 UTC, tiusty commented on houseDatabase/management/commands/pull_mlspin.py
> +                except ValueError:
yea I missed read it, looks good!

2018-02-11 15:24 UTC, merged